### ISSUE TITLE
Pop up at the end of the game

### ISSUE THREAD

**Issue by Qkvad** [Flutter-Buddies/tic_tac_no#33]
Add a pop up at the end of a game with something like: "Good job Player 1 Winner, goodbye Player 2 Loser" and below it, while the confetti goes everywhere, add "Play again" and "Back to menu" buttons.

**Comment by Zambrella** [comment]
![Screenshot_1613401644](https://user-images.githubusercontent.com/53582591/107962991-84987800-6f9f-11eb-9be1-03945faaecbc.png)

How do we feel about something like this?

I have added a 2 second delay after the game is over and before showing this modal so that the user has time to see the board and understand what has happened. This will also give us time to have an animation (or similar) to show the winning 3 squares.

`Quit` takes the user back to the menu and `Play Again` just resets the board with the same game settings.

**Comment by Qkvad** [comment]
I think it's great. 

Maybe instead of `Quit` use `Menu`. It might not be clear what `Quit` does.

PS: score is 2:2 and should be 3:2.

**Comment by slovnicki** [comment]
@Qkvad good catch about the score. I created a separate issue for that bug: https://github.com/Flutter-Buddies/tic_tac_no/issues/49

**Comment by Zambrella** [comment]
Good point about Menu and I see @slovnicki has made an issue (it seems like there is no score data attached to the GameOver state).
